// <auto-generated />
namespace ForumApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_votes_to_comment_post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_votes_to_comment_post));
        
        string IMigrationMetadata.Id
        {
            get { return "202409261825242_added_votes_to_comment_post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
