// <auto-generated />
namespace ForumApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_char_limit_for_content_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_char_limit_for_content_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202409270202553_added_char_limit_for_content_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
