// <auto-generated />
namespace ForumApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_upvotes_downvotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_upvotes_downvotes));
        
        string IMigrationMetadata.Id
        {
            get { return "202409191821597_added_upvotes_downvotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
