// <auto-generated />
namespace ForumApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updated_post_comment_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_post_comment_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202409022024387_updated_post_comment_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
